services:
  upbit-gateway:
    environment:
      UPBIT_ACCESS_KEY: ""
      UPBIT_SECRET_KEY: ""
      UPBIT_ACCESS_KEY_FILE: /run/secrets/upbit_access_key
      UPBIT_SECRET_KEY_FILE: /run/secrets/upbit_secret_key
    secrets:
      - upbit_access_key
      - upbit_secret_key

secrets:
  upbit_access_key:
    file: ${UPBIT_ACCESS_KEY_FILE}
  upbit_secret_key:
    file: ${UPBIT_SECRET_KEY_FILE}
